[package]
name = "nes-rust"
version = "0.1.0"
authors = ["Felix Chapman <aelred717@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4.22"
env_logger = { version = "0.11.5", default-features = false, features = [
    "color",
    "auto-color",
    "humantime",
] }
sdl2 = { version = "0.37.0", features = ["bundled"] }
bitflags = "2.6.0"

[dev-dependencies]
hexdump = "0.1.2"
image = "0.25.2"
yare = "3.0.0"
