[tools]
just = "1"
rust = { version = "nightly", postinstall = "rustup component add rust-src" }
"cargo:wasm-bindgen-cli" = "0.2"
"github:WebAssembly/binaryen" = { version = "129", version_prefix = "version_" }
"npm:vite" = "8"
terraform = "1"

